// Auto-generated by `build.sh` — do not edit manually.
//
// Contains compile-time metadata about the hello user binary layout so the
// kernel can apply read-only page permissions to the code and rodata pages.

/// Number of bytes from the start of the flat binary that should be mapped
/// as read-only (no `WRITABLE` flag). This value is always page-aligned.
///
/// Pages beyond this offset (if any) contain mutable `.data`/`.bss` sections
/// and are mapped as writable.
pub const READONLY_SIZE: usize = 8192;
